name: Ward release to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: dschep/install-poetry-action@v1.3
      with:
        version: 1.0.3
        create_virtualenvs: true
    - name: Publish to PyPI
      run: |
        poetry publish --build --username __token__ --password ${{ secrets.pypi_api_token }}
      working-directory: ${{ github.workspace }}
